// <auto-generated/>

namespace KSPMODAdmin.Core.Utils.Ckan
{
    public class CkanRelation
    {
        public string name = string.Empty;
        public string version = string.Empty;
        public string min_version = string.Empty;
        public string max_version = string.Empty;
    }
}