// <auto-generated/>
using System;

namespace KSPMODAdmin.Core.Utils.Ckan
{
    public class CkanResource
    {
        public Uri homepage;
        public Uri bugtracker;
        public Uri license;
        public Uri ci;
        public Uri kerbalstuff;
        public Uri manual;
    }
}